# Generated by Django 5.1.1 on 2024-10-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_comment_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарий'},
        ),
        migrations.AlterModelOptions(
            name='gamepost',
            options={'ordering': ['-time_create', 'title', '-publish'], 'verbose_name': 'Статьи о играх', 'verbose_name_plural': 'Статьи о играх'},
        ),
    ]
