# Generated by Django 5.1.1 on 2024-10-03 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_comment_options_alter_gamepost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.gamepost', verbose_name='Статья'),
        ),
    ]
