# Generated by Django 5.1.1 on 2024-10-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_comment_article_id_alter_comment_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото1'),
        ),
        migrations.AddField(
            model_name='comment',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото2'),
        ),
    ]
