# Generated by Django 5.1.1 on 2024-10-07 10:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Максимум 255 символов.', max_length=255, verbose_name='Название новости')),
                ('slug', models.SlugField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов'), django.core.validators.MaxLengthValidator(100, message='Максимум 100 символов')], verbose_name='Slug')),
                ('photo', models.ImageField(blank=True, default=None, help_text='Картинка к новости', null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('excerpt', models.TextField(blank=True, help_text='Краткое содержание новости, заполнять не обязательно.', verbose_name='Кратко')),
                ('content', models.TextField(verbose_name='Подробно')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('status', models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-pub_date'],
            },
        ),
    ]
