# Generated by Django 5.1.1 on 2024-10-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_newsblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='newsblock',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='blog.tagnews'),
        ),
    ]
