# Generated by Django 5.1.1 on 2024-10-07 16:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_tagnews_newsblock_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsblock',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Подробно'),
        ),
    ]
