# Generated by Django 5.1.1 on 2024-10-07 16:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_newsblock_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Статья'),
        ),
    ]
